repos:
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.2
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
    -   id: python-no-log-warn
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
    -   id: bandit
